<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = __DIR__;

return [
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\ApiBase'    => $strauss_src . '/j7-dev/wp-plugin-trait/src/classes/ApiBase.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\DTO'        => $strauss_src . '/j7-dev/wp-plugin-trait/src/classes/DTO.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Traits\ApiRegisterTrait' => $strauss_src . '/j7-dev/wp-plugin-trait/src/traits/ApiRegisterTrait.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Traits\PluginTrait' => $strauss_src . '/j7-dev/wp-plugin-trait/src/traits/PluginTrait.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Traits\SingletonTrait' => $strauss_src . '/j7-dev/wp-plugin-trait/src/traits/SingletonTrait.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\Auth'       => $strauss_src . '/j7-dev/wp-utils/src/classes/Auth.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\DB'         => $strauss_src . '/j7-dev/wp-utils/src/classes/DB.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\ErrorLog'   => $strauss_src . '/j7-dev/wp-utils/src/classes/ErrorLog.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\File'       => $strauss_src . '/j7-dev/wp-utils/src/classes/File.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\General'    => $strauss_src . '/j7-dev/wp-utils/src/classes/General.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\Log'        => $strauss_src . '/j7-dev/wp-utils/src/classes/Log.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\LogService' => $strauss_src . '/j7-dev/wp-utils/src/classes/LogService.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\Meta'       => $strauss_src . '/j7-dev/wp-utils/src/classes/Meta.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\Point'      => $strauss_src . '/j7-dev/wp-utils/src/classes/Point.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\PointService' => $strauss_src . '/j7-dev/wp-utils/src/classes/PointService.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\Statement'  => $strauss_src . '/j7-dev/wp-utils/src/classes/Statement.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\UniqueArray' => $strauss_src . '/j7-dev/wp-utils/src/classes/UniqueArray.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\WC\Product' => $strauss_src . '/j7-dev/wp-utils/src/classes/WC/Product.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\WC'         => $strauss_src . '/j7-dev/wp-utils/src/classes/WC.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Classes\WP'         => $strauss_src . '/j7-dev/wp-utils/src/classes/WP.php',
	'J7WpReactPlugin\vendor\J7\WpUtils\Traits\LogTableCreationTrait' => $strauss_src . '/j7-dev/wp-utils/src/traits/LogTableCreationTrait.php',
];
